export const LOGIN = "LOGIN"
export const LOGOUT = "LOGOUT"
export const REGISTER = "REGISTER"
export const AUTH_ERR = "AUTH_ERR"
export const CLR_ERR  = "CLR_ERR"
export const CHECK_AUTH = "CHECK_AUTH"